userconsole_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("users/", include("users.urls"))
]

users/urls.py
from django.urls import path
from . import views


app_name = "users"

urlpatterns = [
    path("", views.user_list, name="list"),  #/users/
    path("create/", views.user_create, name="create"), #/users/create/
    path("<int:user_id>/edit", views.user_update, name="update"),
    path("<int:user_id>/delete/", views.user_delete, name="delete")
    
]

users/models.py
from django.db import models

# Create your models here.

class User(models.Model):

    name = models.CharField(
        max_length=100,
        unique=True,
        null=False,
        blank=False,
        help_text="Användarnman måte vara unik/inte tom"

    )

    def __str__(self):
        return self.name

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .services import add_user, list_users, delete_user, update_user
from .models import User

# Create your views here.


def user_create(request):

    if request.method == "POST":
        name = request.POST.get("name", "")
        success, msg = add_user(name)

        if success:
            return redirect(f"/users/?message={msg}")
        else:
            context = {
                "title": "Skapa ny användare",
                "error": msg,
                "name_value": name,
            }
            return render(request, "users/user_form.html", context)
    
    context = {
        "title": "Skapa ny användare",
        "name_value": "",
    }
    return render(request, "users/user_form.html", context)


def user_list(request):

    users = list_users()
    message = request.GET.get("message")
    
    context = {
        "users": users,
        "message": message,
    }
    return render(request, "users/user_list.html", context)

def user_update(request, user_id):

    user = get_object_or_404(User, id=user_id)

    if request.method == "POST":
        
        new_name = request.POST.get("name", "")
        
        success, msg = update_user(user_id, new_name)

        if success: 
            return redirect(f"/users/?message={msg}")
        else:
              context = {
                "title": "Uppdatera användare",
                "error": msg,
                "name_value": new_name,
            }
        return render(request, "users/user_form.html", context)
    
    context = {
        "title": "Uppdatera användare",
        "name_value": user.name,
    }
    return render(request, "users/user_form.html", context)


def user_delete(request, user_id):
    
    user = get_object_or_404(User, id=user_id)


    if request.method == "POST":
        success, msg = delete_user(user_id)
        return redirect(f"/users/?message={msg}")
    

    context = {
        "user": user,
    }
    return render(request, "users/user_confirm_delete.html", context)

users/templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User console - django</title>
</head>
<body>
    <header>
        <h1>Django userlist</h1>
        <nav>
            <a href="{% url 'users:list' %}">Alla användare</a>
            <a href="{% url 'users:create' %}">Skapa ny användare</a>
        </nav>
    </header>

    {% block content %}
    {% endblock %}

</body>
</html>

users/templates/users/user_confirm_delete.html
{% extends "users/base.html" %}

{%block content %}

<h2>Ta bort användare</h2>

<p>
    Är du säker på att du vill ta bort?
    <strong>{{user.name}}</strong>
</p>

<form method="POST">
    {%csrf_token %}
    <button type="submit">Ja</button>
    <a href="{% url 'users:list' %}">Avbryt</a>

</form>


{% endblock %}

users/templates/users/user_form.html
{% extends "users/base.html" %}

{% block content %}
    <h2>{{title}}</h2>

    
    {% if error %}
        <div class="error">{{error}}</div>
    {% endif %}

    <form method="post">
        {% csrf_token %}
        <label for="name">Användarman</label>
        <input type="text" name="name" id="name" value="{{ name_value|default_if_none:''}}" />
        <br>
        <button type="submit">Spara</button>
    </form>
    {% endblock %}

users/templates/users/user_list.html
{% extends "users/base.html" %}


{% block content %}
    <h2>Alla användare</h2>

    {% if message %}
        <div class="message">{{message}}</div>
    {% endif %}


    {% if users %}
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Namn</th>
                    <th>?</th>
                </tr>
            </thead>
            <tbody>
                {% for user in users %}
                <tr>
                    <td>{{user.id}}</td>
                    <td>{{user.name}}</td>
                    <td>
                        <a href="{% url 'users:update' user.id%}">Redigera</a>
                        <a href="{% url 'users:delete' user.id%}">Radera</a>
                    </td>
                </tr>

                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <p>Inga användare ännu...</p>
        {% endif %}
       
    {% endblock %}